name: Deploy site to GitHub Pages

on:
  push:
    branches:
      - main # ou master, dependendo de como está o nome da sua branch principal

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Pasta do build compilado pelo Vite
          branch: gh-pages # Branch onde os arquivos compilados serão hospedados no GitHub Pages
